/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import model.Relogio;
import model.Usuario;

/**
 *
 * @author computador
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    
    Usuario usuario;
    public TelaInicial(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        setTitle("App Clínica");
        Relogio relogio=new Relogio(lblHora);
        Thread t1=new Thread(relogio);
        t1.start();
        LocalDate date=LocalDate.now();
        DateTimeFormatter formatter=DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String data=date.format(formatter);
        lblData.setText("Data: "+data);
        lblBemVindo.setText("Bem vindo "+usuario.getNome()+"!");
        System.out.println(usuario.getRole());
        if(usuario.getRole().equals("user")){
            menuUsuarios.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHora = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenuItem();
        menuPacientes = new javax.swing.JMenuItem();
        menuMedicos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuConsultas = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/clock.png"))); // NOI18N

        lblBemVindo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBemVindo.setText("Bem vindo!");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblData.setText("Data: ");

        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/application_add.png"))); // NOI18N
        menuCadastro.setText("Cadastro");

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/user.png"))); // NOI18N
        menuUsuarios.setText("Usuários");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuUsuarios);

        menuPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/user_red.png"))); // NOI18N
        menuPacientes.setText("Pacientes");
        menuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPacientesActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPacientes);

        menuMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/doctor.png"))); // NOI18N
        menuMedicos.setText("Médicos");
        menuMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMedicosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuMedicos);

        jMenuBar1.add(menuCadastro);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/calendar.png"))); // NOI18N
        jMenu1.setText("Consultas");

        menuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/calendar_add.png"))); // NOI18N
        menuConsultas.setText("Agendar Consulta");
        menuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasActionPerformed(evt);
            }
        });
        jMenu1.add(menuConsultas);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/calendar_view_day.png"))); // NOI18N
        jMenuItem5.setText("Consultas Hoje");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/help.png"))); // NOI18N
        jMenu4.setText("Ajuda");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/info.jpg"))); // NOI18N
        jMenuItem7.setText("Sobre");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/opcoes.png"))); // NOI18N
        jMenu6.setText("Opções");

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/systemshutdown_94125.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu6.add(menuSair);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBemVindo)
                    .addComponent(lblData)
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lblBemVindo)
                .addGap(56, 56, 56)
                .addComponent(lblData)
                .addGap(78, 78, 78)
                .addComponent(lblHora)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new Sobre().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menuMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMedicosActionPerformed
        new TelaMedicos().setVisible(true);
    }//GEN-LAST:event_menuMedicosActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
       int dialogResult = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja sair?");
        if(dialogResult == JOptionPane.YES_OPTION){
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        new TelaUsuarios().setVisible(true);
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPacientesActionPerformed
        new TelaPacientes().setVisible(true);
    }//GEN-LAST:event_menuPacientesActionPerformed

    private void menuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasActionPerformed
        new telaConsultas().setVisible(true);
    }//GEN-LAST:event_menuConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuConsultas;
    private javax.swing.JMenuItem menuMedicos;
    private javax.swing.JMenuItem menuPacientes;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
